package pl.rk.rosario.enums

enum class BeadRole {
    CROSS,
    INTRO_SIGN_OF_CROSS,
    CREED,
    INTRO_LARGE,
    FAITH,
    HOPE,
    LOVE,
    PRE_DECADE_GLORY,
    PRE_DECADE_OUR_FATHER,
    DECADE_HAIL_MARY,
    DECADE_JESUS_PRAYER,
    DECADE_OUR_FATHER,
    DECADE_GLORY_BE,
    CHAPLET_INTRO_OUR_FATHER,
    CHAPLET_INTRO_HAIL_MARY,
    CHAPLET_INTRO_CREED,
    CHAPLET_DECADE_MAIN,
    CHAPLET_CONCLUSION_TRISAGION,
    CHAPLET_CONCLUSION_TRUST,
    CHAPLET_END_SIGN_OF_CROSS
}
