name: Develop Build and Test

on:
  push:
    branches:
      - develop

jobs:
  android-build:
    uses: ./.github/workflows/android-build.yml
    with:
      run_tests: true
      build_release: false
