name: Develop Build and Test

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

concurrency:
  group: develop-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-build:
    uses: ./.github/workflows/android-build.yml
    with:
      run_tests: true
      build_release: false
      upload_artifacts: true
