name: Release Verification

on:
  push:
    branches:
      - 'release/**'

jobs:
  android-build:
    uses: ./.github/workflows/android-build.yml
    with:
      run_tests: true
      build_release: true
