name: Sync Labels

on:
  schedule:
    -
      cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labels.yml

      -
        name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: false
